SELECT APNT_NO, PT_NAME, A.PT_NO, A.MCDP_CD, DR_NAME, APNT_YMD
FROM APPOINTMENT AS A 
JOIN PATIENT AS P ON P.PT_NO = A.PT_NO
JOIN DOCTOR AS D ON D.DR_ID = A.MDDR_ID
WHERE APNT_CNCL_YMD IS NULL AND A.MCDP_CD = 'CS' AND APNT_YMD LIKE '2022-04-13%'
ORDER BY APNT_YMD;
